using BookManagement.Controllers;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics.CodeAnalysis;

namespace BookManagement.Models
{
    /// <summary>
    /// Book Model
    /// </summary>
    public class Book
    {
        /// <summary>
        /// Id of the Book (Autogenerated identity key)
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID { get; private set; }
        /// <summary>
        /// Title of the book
        /// </summary>
        [Required(ErrorMessage = "Title is required.")]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at most {1} characters long.", MinimumLength = 1)]
        public string Title { get; set; }
        /// <summary>
        /// Author of the book
        /// </summary>
        [Required(ErrorMessage = "Author is required.")]
        [StringLength(50, ErrorMessage = "The {0} must be at least {2} and at most {1} characters long.", MinimumLength = 1)]
        public string Author { get; set; }
    }
}
